### ISSUE TITLE
Main Issue for Official Store

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2-store-website#3]
Continuation from: https://github.com/andersevenrud/OS.js-v2/issues/99

**Comment by junland** [comment]
@andersevenrud Awesome, I'm pretty busy right now with helping Freshman move in at my University so I wont be on much till after next week. Just a headsup :)

**Comment by andersevenrud** [comment]
@junland No pressure here. Whenever you have time :)

**Comment by andersevenrud** [comment]
I'm doing a cleanup of stale issues, so I'm closing this one.
